title: Tom's Travel Pins
logo: assets/florence-1.jpg
description: This is a collection of the places that I've saved to Favourites on Google Maps
google_analytics:
remote_theme: tomwbond/minimal
plugins:
- jekyll-remote-theme